### ISSUE TITLE
Bug when adding computer

### ISSUE THREAD

**Issue by silva-eduardo** [ffquintella/netrisk#22]
When trying to add a new computer (either through the shortcut in the upper right corner of the system, or through the shortcut within the vulnerabilities area. EditHostDialog window) NetRisk is closed when clicking the "Guardar" button.
Searching later the computer is also not added to the base.

**Comment by ffquintella** [comment]
Will verify

**Comment by ffquintella** [comment]
fixed on last commit

**Comment by silva-eduardo** [comment]
Thanks
