### ISSUE TITLE
Match column names in base and "Vulnerabilidades" table

### ISSUE THREAD

**Issue by silva-eduardo** [ffquintella/netrisk#26]
In vulnerabilities area, to facilitate the application of filters, it would be interesting give to table columns the same name displayed in table.
		Ex.: If you want to search for a titulo, the filter would be "titulo == Redirect*"
		Ex.: If you want to search for a nota, the filter would be "nota > 5"

**Comment by ffquintella** [comment]
not possible due to constraints on technology will search for a possible solution to make this better on futher releases
