### ISSUE TITLE
Delay in updating the state of objects

### ISSUE THREAD

**Issue by silva-eduardo** [ffquintella/netrisk#32]
I found that an change in NetRisk, it may take time to be replicated to other users of the tool. Sometimes it is necessary for the other user to close and reopen the application. To facilitate collaborative work, this time could be reduced to the minimum possible.
Note: It was validated through the creation of a new “Entidade”

**Comment by ffquintella** [comment]
This problem is created with the cache we use to avoid the gui becomming to slow. 

I am studing a way to sincronize update messages to avoid this.

**Comment by ffquintella** [comment]
I think it's fixed have to recheck in the future
