### ISSUE TITLE
Change vulnerability states

### ISSUE THREAD

**Issue by silva-eduardo** [ffquintella/netrisk#36]
The tool already has intelligence that does not allow some vulnerability state changes, such as Rejeitada->Verificada or Ajuste solicitado->Verificada, but cases like this may be necessary to correct attribution errors

**Comment by ffquintella** [comment]
We do not want all transitions to be possible. Please show some use cases of this to allow better understanding and avaliation

**Comment by silva-eduardo** [comment]
I want to revert an accidental change in a few cases:

- Vulnerability rejected accidentally
- Vulnerability verified accidentally
- Vulnerability closed accidentally

**Comment by ffquintella** [comment]
Ok I will schedule this to 1.3

**Comment by ffquintella** [comment]
On 1.6 it is now possible to reopen a vulnerability that has been closed to the verified state. This should fix most fo the cases here
