### ISSUE TITLE
Inaccessible buttons when trying to edit “Processo de negócio”

### ISSUE THREAD

**Issue by silva-eduardo** [ffquintella/netrisk#38]
When trying to edit a “Processo de negócio”, the buttons are not visible for activation. The issue occurs in this area and not in others due to the number of “Unidades Organizacionais” displayed on the screen. Similar to Issue #34.

**Comment by ffquintella** [comment]
cannot reproduce please contact me to show a sample

**Comment by ffquintella** [comment]
Will be fixed on next version
