### ISSUE TITLE
Fields at Vulnerabilities table

### ISSUE THREAD

**Issue by silva-eduardo** [ffquintella/netrisk#40]
Include new fields in the Vulnerabilities table (Vulnerabilidades area) and enable filtering by these fields.

The suggested fields are:

- Computador (mainly)
- Time
- Tecnologia

**Comment by ffquintella** [comment]
Fields added

**Comment by ffquintella** [comment]
will be avaliable on the next version

**Comment by silva-eduardo** [comment]
Will they be included with these names (Computador/Time/Tecnologia)?
