### ISSUE TITLE
Problem associating Risco with Vulnerabilidade

### ISSUE THREAD

**Issue by silva-eduardo** [ffquintella/netrisk#50]
After you first edit a Vulnerabilidade in NetRisk, associate the Risco and save. When I re-edit the Vulnerabilidade, it is without the associated risk.

To work around it I re-edit the Vulnerabilidade. It works, but I notice that it associates timedate with the "Última detecção" field

**Comment by silva-eduardo** [comment]
It seems intermittent. It happens about 90% of the time for me

**Comment by ffquintella** [comment]
Fixed in 1.2
