### ISSUE TITLE
Option to disable server

### ISSUE THREAD

**Issue by silva-eduardo** [ffquintella/netrisk#59]
Some servers may be discontinued and this information does not exist at the source of the scans. An interesting option would be to be able to query and deactivate the server in NetRisk. Vulnerabilities associated with the server could be automatically canceled.

**Obs.:** Although this is a more theoretical scenario, you may need to consider automatically reactivating the server if it reappears in the scan listings

**Comment by ffquintella** [comment]
You can delete the server and the vulnerabilities are deleted with it.
