### ISSUE TITLE
Viewing content in "Vulnerabilidades" grid columns

### ISSUE THREAD

**Issue by silva-eduardo** [ffquintella/netrisk#64]
In the "Vulnerabilidades" grid, the information in the following columns is not being displayed as before
Time de Ajuste
Analista
Computador
Aplicação

**Comment by ffquintella** [comment]
Probably a bug in avalonia 11.1.4 ... awaiting confirmation

**Comment by ffquintella** [comment]
Found a work around and will publish in 1.6.2
