### ISSUE TITLE
Computer field in the "Levantamento" area

### ISSUE THREAD

**Issue by silva-eduardo** [ffquintella/netrisk#65]
In the "Levantamento" section, when starting a new "Execuções de Avaliações", the Computer field is assuming the same ID value associated with the Entity.

E.g.: If I fill in the "Entidade" field with meusite.com (123) and save it (regardless of whether or not I fill in the "Computador" field), when I edit the record the "Computador" field takes on a value of the same ID as the "Entidade", for example, server (123).

**Comment by ffquintella** [comment]
Fixed in 1.7
