### ISSUE TITLE
Improve search for "Unidades", "Membros" or "Processos de negócio"

### ISSUE THREAD

**Issue by silva-eduardo** [ffquintella/netrisk#68]
Within the "Entidades" area, it is important to improve the way of searching for associations. Maybe sorting the lists or displaying a search box with auto-completion. The situation was identified in the moments below:

- To associate "Membros" to a "Time" 
- To associate "Unidade Organizacional" to a "Processo de Negócio"
- To associate "Processo de Negócio" or "Responsável" for an "Aplicação"

**Comment by ffquintella** [comment]
Fix in 2.0
